version: '3'
services:
  app:
    image: master2
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/sampleDB
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD= "yes"
      - MYSQL_DATABASE=sampleDB
    ports:
      - 3306:3306
